apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: encryptionconfigurations.apiserver.config.k8s.io
  annotations:
    api-approved.kubernetes.io: "https://github.com/kubernetes/enhancements/pull/1111"
spec:
  group: apiserver.config.k8s.io
  versions:
    - name: v1
      served: true
      storage: true
      schema:
  scope: Namespaced
  names:
    plural: encryptionconfigurations
    singular: encryptionconfiguration
    kind: EncryptionConfiguration
    shortNames:
      - encconfig
