apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  selector:
    app: {{ .Values.deployment.appname }}
  ports:
    - protocol: TCP
      port : {{ .Values.service.spec.ports.port | int }}
      targetPort : {{ .Values.service.spec.ports.targetPort | int }}
