# parametros para o portal-noticias
image:
  repository: aluracursos/portal-noticias
  tag: "1"
  pullPolicy: Always

replicaCount: 2

deployment:
  name: portal-noticias-deployment
  appname: portal-noticias

spec:
  containers:
    name: portal-noticias-chart
    ports:
     name: http
     containerPort: 80
    envFrom:
     configMapRef:
       name: portal-configmap

configMapData:
  name: sistema-configmap
  HOST_DB: svc-db-noticias:3306
  USER_DB: root
  PASS_DB: q1w2e3r4
  DATABASE_DB: empresa

service:
  name: svc-portal-noticias-chart
  spec:    
    ports:
     port: 8080
     targetPort: 80